spring:
   application:
      name: mdt.registry
   servlet:
      multipart:
         maxFileSize: 200MB
         maxRequestSize: 200MB
      
server:
   port: 12985
   error:
      include-message: always

logging:
   level:
      root: INFO
   pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %-40.40logger{39} | %msg%n"


repository:
   aas:
      workspaceDir: D:/Dropbox/Temp/mdt-registry/shells
      cacheSize: 32
   submodel:
      workspaceDir: D:/Dropbox/Temp/mdt-registry/submodels
      cacheSize: 256

instance-manager:
   type: docker
   repositoryEndpointFormat: https://192.168.0.7:%d/api/v3.0
   workspaceDir: D:/Dropbox/Temp/mdt-instances
   
   executor:
      workspaceDir: ${instance-manager.workspaceDir}
      sampleInterval: 3s
      startTimeout: 1m
      
   docker:
      dockerHost: http://localhost:2375