spring:
   application:
      name: mdt.registry
      
server:
   port: 12985
   error:
      include-message: always

logging:
   level:
      root: INFO
   pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %-40.40logger{39} | %msg%n"

jdbc:
   system: postgresql
   host: 192.168.0.7
   port: 5432
   user: mdt
   password: Mdt2024^^
   database: mdt
   
registry:
   workspace_dir: C:/development/mdt/mdt.registry/registry_store
   cache_size:
      aas: 32
      submodel: 256
      
executor:
   repositoryEndpointFormat: https://192.168.0.7:%d/api/v3.0
   workspaceDir: D:/Dropbox/Temp/fa3st-repository
   sampleInterval: 3s
   timeout: 1m