spring:
   application:
      name: mdt.registry
   servlet:
      multipart:
         maxFileSize: 200MB
         maxRequestSize: 200MB
      
server:
   port: 12985
   error:
      include-message: always

logging:
   level:
      root: INFO
   pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %-40.40logger{39} | %msg%n"


rootDir: D:\Dropbox\Temp

registry:
   aas:
      workspaceDir: ${rootDir}/mdt-registry/shells
      cacheSize: 32
   submodel:
      workspaceDir: ${rootDir}/mdt-registry/submodels
      cacheSize: 256
      
repository:
   workspaceDir: ${rootDir}/mdt-repository
   endpoint: http://localhost:${server.port}/api/v3.0

instance-manager:
   type: jar
   repositoryEndpointFormat: https://localhost:%d/api/v3.0
   workspaceDir: ${rootDir}/mdt-instances
   jdbc:
      url: jdbc:h2:${instance-manager.workspaceDir}/descriptors
      user: sa
      password: ""
   
   executor:
      workspaceDir: ${instance-manager.workspaceDir}
      sampleInterval: 3s
      startTimeout: 1m
      
   docker:
      dockerHost: http://localhost:2375
      mountPrefix: ${rootDir}/mdt-instances